import unittest

"""
    This question is asked by Google. You are given two strings, s and t which only
    consist of lowercase letters. t is generated by shuffling the letters in s as
    well as potentially adding an additional random character. Return the letter
    that was randomly added to t if it exists, otherwise, return empty string.

    Note: You may assume that at most one additional character can be added to t.  
"""
class TestSpotTheDifference(unittest.TestCase):
  def spot_the_difference(self, s: str, t: str) -> str:
    if len(s) is 0 or len(t) is 0: return ''
    return ''

  def test_spot_the_difference(self):
    self.assertEqual(self.spot_the_difference('', ''), '')
    self.assertEqual(self.spot_the_difference('foobar', 'barfoot'), 't')
    self.assertEqual(self.spot_the_difference('ide', 'idea'), 'a')
    self.assertEqual(self.spot_the_difference('coding', 'ingcod'), '')

if __name__ == '__main__':
  unittest.main()